    select* from googleplaystore;

# Total number of apps present in playstore -- 248
    select count(distinct app)
    from googleplaystore;

# Number of Category Present in Datset -- 5
    select count(distinct category) 
    from googleplaystore;

# All category within the number of apps in them 
    select category , count(*) as Number_of_apps
    from googleplaystore
    group by Category;

# Average Rating and Average Size of all the Apps
    select avg(rating) as Average_rating,avg(size) as average_size_inkb
    from googleplaystore
    group by rating;

# Overview of all the categories wrt number of installs, least rated app, number of free app and number of paid apps in that category 
	select category, min(installs) as least_rating, max(installs) as large_install
    from googleplaystore
    group by Category;

#-1. Which are the top 10 highest rated apps in the given available datasets 
    select app,rating 
    from googleplaystore
    order by rating desc
    limit 10 ;
 
#-2 What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top
    select count(installs),reviews,app
    from googleplaystore
    group by reviews 
    order by reviews desc;
  
#-3 Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
	 select app,reviews,Category
	 from googleplaystore
	 order by reviews desc;

#-4 What is the total amount of revenue generated by the google play store by hosting apps? (Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
	 select sum(Installs*price),app
	 from googleplaystore;
   
#-5 Which Category of google play store apps has the highest number of installs? Also, find out the total number of installs for that particular category.
     select category ,installs
     from googleplaystore
     order by installs desc;
   
#-6 Which Genre has the most number of published apps?
     select count(genres),app
     from googleplaystore
     group by  Genres;
   
#-7 Find the count of apps in each content rating based on App type
     select count(app),Content_Rating,app,type
     from googleplaystore
     group by Type;
   
#-8 Create a new column to bucket rating to high(4-5), medium(2-4), low(0-2). Return the app names
     select app,rating,
     CASE
	 when rating between 4 and 5 then 'High'
	 when rating between 2 and 4 then 'medium'
	 else 'Low'
	 end 
	 from googleplaystore;
      
#-9 Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top 
	 select distinct app,installs,category
	 from googleplaystore
	 order by Installs desc;
      
#-10 List all non-entertainment and non-education apps that are rated by everyone or teen
	 select*
	 from googleplaystore
	 where category not in ('Entertainment','non-education')
	 and Content_Rating in ('Everyone','teen');
   
#-11 List all the apps whose app names contain the letter “i” or start with the letter “D”
	 select*
	 from googleplaystore
	 where app like'%i%' or app like '%D%';
   
#-12  Return the app names, categories, sizes, release dates (rename it to “Last Updated”) of apps whose app names have more than 1 word, and whose categories are music and social, and whose sizes are bigger than 10. Order the output result by maximum installs in descending order, then release dates in ascending order.
	 select app,category, size, LastUpdate as last_updated
	 from googleplaystore
	 where Category = 'ART_AND_DESIGN'
	 and app like '_%'
	 and size > 10;
   
#-13  Find the number of apps in each category that have a rating greater than the average rating
	 select count(app),category,rating
	 from googleplaystore
	 group by category having rating > avg(rating);
   
#-14 List the largest app size within each app category.
	select max(app),size,category
	from googleplaystore
	group by app
	order by app desc;
   
   
   
   
   
   
   
   
   
   
   
   
   
   